from benchmarking.functions import (
    beale,
    booth,
    branin,
    bukin_n6,
    eggholder,
    goldstein_price,
    hartmann,
    himmelblau,
    holder_table,
    matyas,
    rosenbrock,
    schwefel,
    shekel,
    shubert,
    six_hump_camel,
    sphere,
    styblinski_tang,
    three_hump_camel,
)

optima = {
    "beale": beale.beale_min(),
    "booth": booth.booth_min(),
    "branin": branin.branin_min(),
    "bukin_n6": bukin_n6.bukin_n6_min(),
    "eggholder": eggholder.eggholder_min(),
    "goldstein_price": goldstein_price.goldstein_price_min(),
    "hartmann3D": hartmann.hartmann_min(dimensions=3),
    "hartmann6D": hartmann.hartmann_min(dimensions=6),
    "himmelblau": himmelblau.himmelblau_min(),
    "holder_table": holder_table.holder_table_min(),
    "imine": -0.1664,
    "matyas": matyas.matyas_min(),
    "rosenbrock": rosenbrock.rosenbrock_min(),
    "schwefel2D": schwefel.schwefel_min(),
    "schwefel3D": schwefel.schwefel_min(),
    "shekel5": shekel.shekel_min(5),
    "shekel7": shekel.shekel_min(7),
    "shekel10": shekel.shekel_min(10),
    "shubert": shubert.shubert_min(),
    "six_hump_camel": six_hump_camel.six_hump_camel_min(),
    "sphere": sphere.sphere_min(),
    "styblinski_tang_3D": styblinski_tang.styblinski_tang_min(3),
    "three_hump_camel": three_hump_camel.three_hump_camel_min(),
    "pk": -65.3102665008655,
    "aldol_yield_product": -89.7,
    "aldol_yield_dba": 0.11466,
    "aldol_sty": -285.3,
    "aldol_lit_sty": -237.43,
    "aldol_lit_efactor": -33.7,
}
