from benchmarking.functions import (
    beale,
    booth,
    branin,
    bukin_n6,
    eggholder,
    goldstein_price,
    hartmann,
    himmelblau,
    holder_table,
    matyas,
    rosenbrock,
    schwefel,
    shekel,
    shubert,
    six_hump_camel,
    sphere,
    styblinski_tang,
    three_hump_camel,
)

optima = {
    "beale": beale.Beale().global_minima[0].value,
    "booth": booth.Booth().global_minima[0].value,
    "branin": branin.Branin().global_minima[0].value,
    "bukin_n6": bukin_n6.BukinN6().global_minima[0].value,
    "eggholder": eggholder.Eggholder().global_minima[0].value,
    "goldstein_price": goldstein_price.GoldsteinPrice().global_minima[0].value,
    "hartmann3D": hartmann.Hartmann3D().global_minima[0].value,
    "hartmann6D": hartmann.Hartmann6D().global_minima[0].value,
    "himmelblau": himmelblau.Himmelblau().global_minima[0].value,
    "holder_table": holder_table.HolderTable().global_minima[0].value,
    "imine": -0.1664,
    "matyas": matyas.Matyas().global_minima[0].value,
    "rosenbrock": rosenbrock.Rosenbrock().global_minima[0].value,
    "schwefel2D": schwefel.Schwefel(dim=2).global_minima[0].value,
    "schwefel3D": schwefel.Schwefel(dim=3).global_minima[0].value,
    "shekel5": shekel.Shekel(m=5).global_minima[0].value,
    "shekel7": shekel.Shekel(m=7).global_minima[0].value,
    "shekel10": shekel.Shekel(m=10).global_minima[0].value,
    "shubert": shubert.Shubert().global_minima[0].value,
    "six_hump_camel": six_hump_camel.SixHumpCamel().global_minima[0].value,
    "sphere": sphere.Sphere().global_minima[0].value,
    "styblinski_tang_3D": styblinski_tang.StyblinskiTang(dim=3)
    .global_minima[0]
    .value,
    "three_hump_camel": three_hump_camel.ThreeHumpCamel()
    .global_minima[0]
    .value,
    "pk": -65.3102665008655,
    "aldol_yield_product": -89.7,
    "aldol_yield_dba": 0.11466,
    "aldol_sty": -285.3,
    "aldol_lit_sty": -237.43,
    "aldol_lit_efactor": -33.7,
}
